export const LEO_ACTIVITY_THEMES = {
  leo_first_check: {
    title: "Leo's First Sound Check",
    titleKey: "first_sound_check",
    animalMessage: "Let's find your sound path!",
    animalMessageKey: "lets_find_sound_path",
    primaryColor: "#15803d",
    secondaryColor: "#f59e0b",
    collectible: "sound gem",
    collectibleKey: "sound_gems",
    collectibleIcon: "Gem",
    rewardName: "Sound Path Badge",
    rewardNameKey: "sound_path_badge",
    taskLabel: "Sound Check",
  },
  leo_first_sound_hunt: {
    title: "First Sound Hunt",
    titleKey: "activity_first_sound_hunt_title",
    animalMessage: "Let's find the first sound!",
    animalMessageKey: "activity_first_sound_hunt_guide",
    primaryColor: "#16a34a",
    secondaryColor: "#f59e0b",
    collectible: "leaf",
    collectibleKey: "activity_first_sound_hunt_collectible",
    collectibleIcon: "Leaf",
    rewardName: "First Sound Badge",
    rewardNameKey: "activity_first_sound_hunt_reward",
    taskLabel: "First Sound",
  },
  leo_echo_roar: {
    title: "Echo Roar",
    titleKey: "activity_echo_roar_title",
    animalMessage: "Listen and roar the word back!",
    animalMessageKey: "activity_echo_roar_guide",
    primaryColor: "#0d9488",
    secondaryColor: "#f97316",
    collectible: "roar gem",
    collectibleKey: "activity_echo_roar_collectible",
    collectibleIcon: "Gem",
    rewardName: "Echo Roar Badge",
    rewardNameKey: "activity_echo_roar_reward",
    taskLabel: "Echo",
  },
  leo_robot_words: {
    title: "Robot Word Safari",
    titleKey: "activity_robot_words_title",
    animalMessage: "Read the funny robot words!",
    animalMessageKey: "activity_robot_words_guide",
    primaryColor: "#2563eb",
    secondaryColor: "#f59e0b",
    collectible: "robot bolt",
    collectibleKey: "activity_robot_words_collectible",
    collectibleIcon: "Bolt",
    rewardName: "Robot Word Badge",
    rewardNameKey: "activity_robot_words_reward",
    taskLabel: "Robot Word",
  },
  leo_sound_twins: {
    title: "Sound Twins",
    titleKey: "activity_sound_twins_title",
    animalMessage: "Choose the sound twin carefully!",
    animalMessageKey: "activity_sound_twins_guide",
    primaryColor: "#7c3aed",
    secondaryColor: "#f59e0b",
    collectible: "twin shell",
    collectibleKey: "activity_sound_twins_collectible",
    collectibleIcon: "Shell",
    rewardName: "Sound Twins Badge",
    rewardNameKey: "activity_sound_twins_reward",
    taskLabel: "Sound Twins",
  },
  leo_story_roar: {
    title: "Story Roar Trail",
    titleKey: "activity_story_roar_title",
    animalMessage: "Read the story with Leo!",
    animalMessageKey: "activity_story_roar_guide",
    primaryColor: "#be123c",
    secondaryColor: "#f59e0b",
    collectible: "story scroll",
    collectibleKey: "activity_story_roar_collectible",
    collectibleIcon: "Scroll",
    rewardName: "Story Roar Badge",
    rewardNameKey: "activity_story_roar_reward",
    taskLabel: "Story",
  },
};

export const DEFAULT_LEO_THEME = {
  title: "Leo's Sound Safari",
  titleKey: "leo_sound_safari_title",
  animalMessage: "Follow Leo through the jungle path!",
  animalMessageKey: "follow_sound_path",
  primaryColor: "#15803d",
  secondaryColor: "#f59e0b",
  collectible: "sound gem",
  collectibleKey: "sound_gems",
  collectibleIcon: "Gem",
  rewardName: "Jungle Sound Badge",
  rewardNameKey: "jungle_sound_badge",
  taskLabel: "Sound",
};

export const getLeoActivityTheme = (activityId) =>
  LEO_ACTIVITY_THEMES[activityId] || DEFAULT_LEO_THEME;
